spring:
    profiles:
        active:
        - dev
---
server:
  port: 7001
spring:
  application:
    name: role-eureka7001
    profiles: dev
eureka:
  instance:
    #hostname: localhost #eureka服务端的实例名称
    hostname: eureka7001.com #集群
  client:
    register-with-eureka: false #false表示不向注册中心注册自己个
    fetch-registry: false #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索eureka服务端
    service-url:
      #defaultZone: http://${eureka7001.instance.hostname}:${server.port}/eureka7001/  #设置与eureka服务端交互的地址查询服务和注册服务
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
spring:
  application:
    name: role-eureka7001
    profiles: test
eureka:
  instance:
    #hostname: localhost #eureka服务端的实例名称
    hostname: eureka7001.com 
  client:
    register-with-eureka: false #false表示不向注册中心注册自己个
    fetch-registry: false #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索eureka服务端
    service-url:
      #defaultZone: http://${eureka7001.instance.hostname}:${server.port}/eureka7001/  #设置与eureka服务端交互的地址查询服务和注册服务
      defaultZone: http://eureka7001.com:7001/eureka/
