spring:
    profiles:
        active:
        - dev
---
server:
    port: 8201
spring:
    profiles: dev #策略
    application:
        name: springcloud-role-config
eureka:
    client:
        service-url:
            defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
    port: 8202
spring:
    profiles: test #策略
    application:
        name: springcloud-role-config
eureka:
    client:
        service-url:
            defaultZone: http://eureka-test.com:7001/eureka/